# Generated by Django 4.2.26 on 2025-11-28 16:23

from django.db import migrations, models
import translator.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PDFTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(upload_to=translator.models.pdf_upload_path, verbose_name='Archivo PDF')),
                ('docx_file', models.FileField(blank=True, null=True, upload_to=translator.models.docx_upload_path, verbose_name='Archivo traducido')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completado'), ('error', 'Error')], default='pending', max_length=20, verbose_name='Estado')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Mensaje de error')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de finalización')),
            ],
            options={
                'verbose_name': 'Traducción de PDF',
                'verbose_name_plural': 'Traducciones de PDF',
                'ordering': ['-created_at'],
            },
        ),
    ]
