# Generated by Django 4.2.26 on 2025-11-28 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdftranslation',
            name='cancel_requested',
            field=models.BooleanField(default=False, verbose_name='Cancelación solicitada'),
        ),
        migrations.AddField(
            model_name='pdftranslation',
            name='progress',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Progreso (%)'),
        ),
        migrations.AddField(
            model_name='pdftranslation',
            name='target_language',
            field=models.CharField(default='es', max_length=10, verbose_name='Idioma destino'),
        ),
    ]
