# Generated by Django 4.2.26 on 2025-11-28 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translator', '0002_pdftranslation_cancel_requested_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdftranslation',
            name='current_chunk',
            field=models.PositiveIntegerField(default=0, verbose_name='Parte actual'),
        ),
        migrations.AddField(
            model_name='pdftranslation',
            name='current_page',
            field=models.PositiveIntegerField(default=0, verbose_name='Página actual'),
        ),
        migrations.AddField(
            model_name='pdftranslation',
            name='status_message',
            field=models.CharField(blank=True, max_length=255, verbose_name='Mensaje de estado'),
        ),
        migrations.AddField(
            model_name='pdftranslation',
            name='total_chunks',
            field=models.PositiveIntegerField(default=0, verbose_name='Total de partes'),
        ),
        migrations.AddField(
            model_name='pdftranslation',
            name='total_pages',
            field=models.PositiveIntegerField(default=0, verbose_name='Total de páginas'),
        ),
    ]
