# Generated by Django 4.2.26 on 2025-11-28 20:16

from django.db import migrations, models
import translator.models


class Migration(migrations.Migration):

    dependencies = [
        ('translator', '0003_pdftranslation_current_chunk_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdftranslation',
            name='docx_file',
        ),
        migrations.AddField(
            model_name='pdftranslation',
            name='translated_pdf',
            field=models.FileField(blank=True, null=True, upload_to=translator.models.translated_pdf_upload_path, verbose_name='PDF traducido'),
        ),
    ]
